image: python:3.9

variables:
  SONAR_TOKEN: $SONAR_TOKEN

before_script:
  - python -m pip install -r requirements.txt

test:
  script:
    - python -m pytest test.py

sonarqube_analysis:
  script:
    - python -m pytest --cov=app.py --cov-report=xml test.py
    - python -m coverage xml -i
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  dependencies:
    - test

build_image:
  script:
    - docker build -t myapp .
  dependencies:
    - test
    - sonarqube_analysis

push_image:
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push myapp
  dependencies:
    - build_image

