name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubernetes-version: latest
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: latest
      - name: Login to Docker registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and push image
        run: |
          docker build -t myuser/myapp:latest .
          docker push myuser/myapp:latest
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
